// DO NOT EDIT. This file is generated by Fresh but maintained manually here.
// It defines route and island modules for the admin dashboard.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/login.tsx";
import * as $2 from "./routes/logout.ts";
import * as $3 from "./routes/api/auth.ts";
import * as $4 from "./routes/api/graphql.ts";
import * as $5 from "./routes/tables/index.tsx";
import * as $6 from "./routes/tables/[table].tsx";
import * as $7 from "./routes/monitoring/index.tsx";
import * as $8 from "./routes/monitoring/websocket.tsx";
import * as $9 from "./routes/settings/index.tsx";

import * as $$0 from "./islands/TableBrowser.tsx";
import * as $$1 from "./islands/GraphQLPlayground.tsx";
import * as $$2 from "./islands/LiveFeed.tsx";
import * as $$3 from "./islands/QueryBuilder.tsx";
import * as $$4 from "./islands/DataGrid.tsx";

import config from "./fresh.config.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest: Manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/login.tsx": $1,
    "./routes/logout.ts": $2,
    "./routes/api/auth.ts": $3,
    "./routes/api/graphql.ts": $4,
    "./routes/tables/index.tsx": $5,
    "./routes/tables/[table].tsx": $6,
    "./routes/monitoring/index.tsx": $7,
    "./routes/monitoring/websocket.tsx": $8,
    "./routes/settings/index.tsx": $9,
  },
  islands: {
    "./islands/TableBrowser.tsx": $$0,
    "./islands/GraphQLPlayground.tsx": $$1,
    "./islands/LiveFeed.tsx": $$2,
    "./islands/QueryBuilder.tsx": $$3,
    "./islands/DataGrid.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
